name: Build containers on workflow_dispatch

on:
  workflow_dispatch:
    branches: [ main ]
    inputs:
      build_dir:
        description : 'Build Directory'
        required    : true
        default     : ''
      dockerfile:
        description : 'Dockerfile Name'
        required    : true
        default     : ''
      image_repo:
        description : 'Image Repository'
        required    : true
        default     : ''
      image_tag:
        description : "Image Tag"
        required    : true
        default     : ''
      id:
        description: 'run identifier'
        required: false

jobs:
  choose-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.choose-runner.outputs.runner }}
    steps:
      - id: choose-runner
        uses: QCDIS/choose-action-runner@v1
        with:
          preferred-runner: ${{ vars.PREFERRED_ACTIONS_RUNNER }}
          fallback-runner: ubuntu-latest
          github-token: ${{ secrets.RUNNER_ACCESS_TOKEN }}

  build-push:
    needs: [choose-runner]
    runs-on: ${{ needs.choose-runner.outputs.runner }}
    name: ${{github.event.inputs.id}}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: actions/checkout@v2
      - name: Build and push image
        run:  |
          echo ${{ github.event.inputs.dockerfile }} --tag ${{ github.event.inputs.image_repo }}/${{ github.event.inputs.image_tag }}
          dir="${{ github.event.inputs.build_dir }}"
          if [ "$dir" != ".github/workflows" ]; then
            cd $dir
            docker build . --file ${{ github.event.inputs.dockerfile }} --tag ${{ github.event.inputs.image_repo }}/${{ github.event.inputs.image_tag }}
            docker push ${{ github.event.inputs.image_repo }}/${{ github.event.inputs.image_tag }}
          fi
